# oh-my-zsh
ZSH_THEME="gianu"
ZSH=$HOME/.oh-my-zsh
plugins=(git jsontools sudo urltools)
source $ZSH/oh-my-zsh.sh

# general shell config
zstyle ':completion:*' special-dirs true

# allow local modifications
if [[ -a ~/.zshrc-local ]]; then
	source ~/.zshrc-local
fi

# load catkin workspace
if [[ -a ~/catkin_ws/devel/setup.zsh ]]; then
  source ~/catkin_ws/devel/setup.zsh
fi

# load ROS environment
source /opt/ros/melodic/setup.zsh

