---
- name: Install ROS ppa
  copy:
    src: ros-latest.list
    dest: /etc/apt/sources.list.d/ros-latest.list

- name: Add ROS signing key
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: 421C365BD9FF1F717815A3895523BAEEB01FA116
  register: result
  until: result | success

- name: Install ROS
  apt:
    update_cache: yes
    pkg: ros-kinetic-desktop-full
    state: present
  register: result
  until: result | success

- name: Install catkin
  apt:
    update_cache: yes
    pkg: ros-kinetic-catkin
    state: present
  register: result
  until: result | success

- name: Create catkin workspace dir
  file:
    path: /home/ubuntu/catkin_ws/src
    state: directory
    owner: ubuntu
    group: ubuntu

- name: Create catkin workspace
  command: /bin/zsh -c "source /opt/ros/kinetic/setup.zsh && catkin_make"
  become: yes
  become_user: ubuntu
  args:
    chdir: /home/ubuntu/catkin_ws

