---
- name: Ensure user is part of plugdev group
  user:
    name=ubuntu
    groups=plugdev
    append=yes

- name: Ensure udev rules.d exists
  file:
    path: /etc/udev/rules.d
    state: directory

- name: Upload pico udev rule
  copy:
    src=10-royale-ubuntu.rules
    dest=/etc/udev/rules.d/10-royale-ubuntu.rules

- name: Install i2c-tools
  apt:
    pkg: i2c-tools
    state: present
  register: result
  until: result | success

- name: Ensure user is part of the i2c group
  user:
    name=ubuntu
    groups=i2c
    append=yes
